### ISSUE TITLE
Turn this into docs.pyvec.org

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/docs.pyvec.org#53]
- [x] rename repository
- [x] create redirects
- [x] setup docs.pyvec.org to point at the generated docs
- [x] link docs.pyvec.org from the pyvec.org website
- [x] link docs.pyvec.org from the python.cz website
- [x] re-purpose the repo, adjust contents to reflect the change
- [x] add place where other Pyvec internal guidelines ("směrnice") will go
- [ ] ~~move docs from https://github.com/pyvec/documents here or to our Google Drive and delete the repository~~ ➡️ https://github.com/pyvec/docs.pyvec.org/issues/67
- [ ] ~~add new (commented) Pyvec bylaws~~ ➡️ https://github.com/pyvec/docs.pyvec.org/issues/57
- [ ] ~~add docs about how Pyvec deals with finances~~ ➡️ https://github.com/pyvec/guide/issues/52

**Comment by honzajavorek** [comment]
Closed by https://github.com/pyvec/docs.pyvec.org/pull/69
